version: '3.1'

services:

  wordpress:
    image: wordpress:php7.4-apache
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      # Referenced in wp-config.php
      WP_DB_HOST: db
      WP_DB_USER: wordpress
      WP_DB_PASSWORD: wordpress
      WP_DB_NAME: wordpress
      WP_PHPUNIT__TESTS_CONFIG: /var/www/html/wp-tests-config.php
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

volumes:
  db: